components/ui/Tabs.stories.tsx
components/ui/Tabs.tsx
package-lock.json
package.json

- Close #9 
- 기능 : 탭 컴포넌트를 생성하였습니다.
- issue : #9 
- 탭 컴포넌트 생성
- 탭의 색상을 변경할 수 있도록 개발했습니다.
- 우선 storybook에서 타입 강제를 해놓은 상태입니다. 만약 개발에서도 문제가 생긴다면 디렉터님께 추가 피드백 받도록 하겠습니다.
- storyObj의 typeof를 'meta'에서 'Tabs'로 명시적 지정하였습니다.
- radix/ui 모듈을 찾지 못하는 오류가 있어 '@radix-ui/react-tabs'를 다운 받았습니다. 참고 부탁드립니다.
- 추가적인 기능이 필요하다고 생각 되시면 말씀 부탁드립니다!

feat: Tab 컴포넌트 생성

---

components/ui/Input.stories.tsx
components/ui/Input.tsx

- Close #16
- 기능 : Input 컴포넌트 search, icon props 추가했습니다. 
- issue : #16 
- icon이 있는 input을 사용하고 싶은 경우, icon이 있는 컴포넌트를 Input의 icon 속성으로 넘겨주면 됩니다. 
- search input을 사용하고 싶은 경우, Input의 search 속성만 true로 주면 됩니다.

refactor: Input 컴포넌트 search, icon props 추가

---

components/ui/ImageCard.stories.tsx
components/ui/ImageCard.tsx

- Close #12 
- 기능 : 이미지 카드 컴포넌트를 생성하였습니다. 
- issue : #12
- 이미지 카드 컴포넌트를 크기별로 구현하였습니다. 
- size 속성에 sm, md, lg 를 부여하면 크기별 렌더링이 가능합니다. 
- 이미지 카드는 이미지가 필수입니다. src 속성에 이미지 주소를 넣어야 합니다. 
- ImageCardDescription은 설명이 필요한 경우에만 추가하면 됩니다. 
- ImageCardDescription 의 Text 에는 lineClamp={1} 속성이 static 하게 지정되어 있습니다. 해당 속성은 1줄이 넘어가면 말줄임표를 사용해달라는 속성입니다. 기획 상 이미지 카드에 1줄 이상인 설명이 필요하지 않을 것 같아 우선 이렇게 지정하였으나, 추후 기획이 변경이 필요하다면  수정하도록 하겠습니다.

feat: 이미지 카드 컴포넌트 생성

---

components/ui/Header.stories.tsx
components/ui/Header.tsx
components/ui/ImageCard.tsx
components/ui/Input.stories.tsx
components/ui/Input.tsx
components/ui/Text.stories.tsx
components/ui/Text.tsx
types/layoutTypes.ts

- Close #10 
- 기능 : 유저 상태에 따른 헤더를 구현하였습니다.  
- issue : #10 
- Text 컴포넌트에 LinkText 컴포넌트를 추가하여 이동할 수 있는 텍스트 컴포넌트를 생성하였습니다. 
- Text 컴포넌트에 class를 추가할 수 있도록 변경하였습니다. 
- Input의 Search Input 아이콘의 크기를 변경하였습니다. 
- 비로그인
- 로그인 && 동호회 미가입
- 로그인 && 동호회 가입
- 로고와 프로필 사진은 추후 변경 필요합니다 .
- 디폴트 프로필 사진은 어떻게 할지 논의가 필요합니다.

feat: 헤더 컴포넌트 생성

---

app/page.tsx
components/DayCell.tsx
components/ui/calendar.tsx
package-lock.json
package.json

- Close #35 
- 기능 : 캘린더 컴포넌트를 생성하였습니다. 
- issue : #35
- shadcn에서 calendar 컴포넌트 생성하여 작업했습니다. 
- DayCell이라는 컴포넌트를 통해 날짜 셀의 컴포넌트를 커스텀할 수 있습니다. 
- 스타일링 작업은 새로 이슈 파서 작업하겠습니다. 
- TODO: 백엔드 연동 전 mock data type 정의

feat: 캘린더 컴포넌트 연동

---

app/(header)/club/member/MemberDropdown.tsx
app/(header)/club/member/OneMemberInfo.tsx
app/(header)/club/member/page.tsx
components/ui/IconButton.tsx

- Close #41 
- 기능 : 멤버 페이지를 생성하였습니다. 
- issue : #41 
- 멤버들의 이미지, 티어, 이름, 전적, 관리 버튼을 구현 하였습니다.
- 스크롤을 통해 멤버들을 쭉 확인 할 수 있도록 구현하였습니다.
- 햄버거 버튼 클릭 시 멤버를 관리할 수 있는 dropdown을 만들었습니다. 다만 내부 div의 height를 지정해 준 상태이기 때문에  맨 아래 멤버의 햄버거 버튼 클릭 시 스크롤을 통해서 dropdown을 확인 할 수 있습니다.
- 우선 API 연동이 안되어 있는 부분이기 때문에 p태그를 이용해 내용을 채워줬습니다. 추후 티어에 따른 이미지를 넣어주는 로직과 정보를 받아오는 로직을 추가 구현해야 합니다.

feat: 멤버 페이지 생성

---

app/(header)/club/layout.tsx
middleware.ts

- Close #38
- 기능 : 새로고침 했을 때 탭 활성화 되지 않는 오류 해결하였습니다. 
- issue : #38 
- middleware 파일 생성하여 files 와 APIs 가 아닌 파일에 한해 url을 응답 헤더에 set 해주었습니다. 
- layout에서는 아래 사진과 같이 header에서 x-current-path 가져 와서 현재 url을 가져올 수 있습니다. 이렇게 가져온 url은 /club/intro 처럼 / 로 시작합니다.

fix: 새로고침 했을 때 url 에 따라 탭 활성화되도록 수정

---

app/(header)/my/MyOneGameResult.tsx
app/(header)/my/page.tsx

- Close #48 
- 기능 : 마이 페이지를 생성하였습니다.
- issue : #48 
- 마이페이지에 필요한 사용자 정보와 해당 사용자의 경기 결과 UI를 구현하였습니다.

feat: 마이 페이지 생성

---

app/(header)/club/schedule/ScheduleList.tsx
app/(header)/club/schedule/league/[leagueId]/page.tsx
utils/getTierWithEmoji.ts

- Close #75 
- 기능 : 리그 정보를 다루는 페이지의 UI를 개선시켰습니다. 
- issue : #75 
- 티어 이모지와 글자를 렌더링하는 함수를 따로 빼어 utils 파일 안에 두었습니다. 
- 위 작업으로, getTierWithEmoji를 사용하는 함수에 변경사항이 있습니다. 
- 빠진 부분이 있으면 말해주세요!

design: 리그 정보 UI 작업

---

app/(header)/my-club/schedule/[leagueId]/match/MatchProfileDoubles.tsx
app/(header)/my-club/schedule/[leagueId]/match/MatchProfileSingles.tsx
app/(header)/my-club/schedule/[leagueId]/match/MatchScoreModalDoubles.tsx
app/(header)/my-club/schedule/[leagueId]/match/MatchScoreModalSingles.tsx
app/(header)/my-club/schedule/[leagueId]/match/page.tsx
app/(header)/my-club/schedule/[leagueId]/page.tsx

- Close #111 
- 기능 : 대진표 화면 및 기능 구현
- issue : #111
- 단식/복식 나눠서 경기 상대 및 진행상황, 현재 세트 스코어가 보이도록 하였습니다.
- 하나의 경기를 누르게 되면 경기 상세 페이지로 넘어가 세트별 점수를 조절할 수 있고, 점수 입력이 완료되면 이긴 사람의 세트 스코어가 오르도록 구현하였습니다.
https://github.com/user-attachments/assets/6ff19c63-a325-4972-9d66-7643a4113ecf
- 현재 게임 생성 후 진행 상황, 세트 스코어에 대한 기능은 구현되어 있지 않은 상태입니다. API 연동을 하며 수정이 필요합니다.
- 경기 상세 모달에서 세트 점수에 대한 수정은 구현되어 있지 않습니다. 추후 구현이 필요합니다.
- UI가 제대로 구현되어 있지 않습니다. 추후 이야기를 통해 변경이 필요합니다.

feat: 대진표 화면 및 기능 구현

---

app/(header)/my-club/member/MemberInfo.tsx
app/(header)/my-club/member/page.tsx
lib/api/functions/clubMemberFn.ts
lib/api/hooks/clubMemberHook.ts

- Close #113 
- 기능 : 멤버 페이지 API 연동
- issue : #113
- 멤버 페이지에 API를 연동하였습니다.
- 추가적으로 직책이 보여야 될 것 같아 직책을 추가하였습니다.
- 현재 path variable에 clubId가 들어가는 것에 대해 정해지지 않아 임의로 clubid가 1인 것으로 가정하고 API 호출을 하였습니다.
- API 호출한 후에 컴포넌트를 불러올 때 타입을 'as'를 통해 강제로 지정해주고 있습니다. 이 부분도 추후웨 리팩토링 때 undefined를 해결할 다른 방법을 생각해봐야 될 것 같습니다.

feat: 멤버 페이지 API 연동

---

app/(header)/club/[clubId]/layout.tsx
app/(header)/club/[clubId]/manage/page.tsx
components/common/clubInfoInput/ClubInfoInputName.tsx
lib/api/functions/clubFn.ts
lib/api/hooks/clubHook.ts

- Close #114 
- 기능 : 동호회 관리 페이지 API 연동
- issue : #114
- 동호회 이름, 소개, 이미지를 변경할 수 있도록 하였습니다.
- 변경이 완료 / 실패는 alert를 통해 사용자가 확인할 수 있도록 하였습니다.
- react-hook-form을 이용하여 입력이 무조건 있을 수 있도록 하였습니다.

feat: 동호회 관리 페이지 API 연동

---

app/(header)/club/[clubId]/schedule/ScheduleList.tsx
app/(header)/club/[clubId]/schedule/page.tsx
constants/loginOauthUrl.ts
lib/api/functions/leagueFn.ts
lib/api/hooks/leagueHook.ts
schemas/schema.d.ts
utils/getLeagueType.ts

- Close #134
- 기능 : 일별 경기 일정 조회 구현
- issue : #134
- 일별 일정 조회 연동
- 스케줄 요소 정렬
- 스케줄 없을 때 처리
- 일 선택 시 월도 같이 fetch하는 에러 해결

feat: 일별 조회 api 연동

---

app/(header)/club/[clubId]/schedule/[leagueId]/match/page.tsx
app/(header)/club/[clubId]/schedule/[leagueId]/page.tsx
constants/loginOauthUrl.ts
lib/api/functions/matchFn.ts
lib/api/hooks/matchHook.ts
schemas/schema.d.ts

- Close #154 
- 기능 : 대진표 생성 api 연동
- issue : #154 
- 대진표가 생성 되기 전이라면 대진표 생성하기 버튼이, 생성 후라면 대진표 보기 버튼이 렌더링 됩니다.

feat: 대진표 생성 api 연동

---

components/DayCarousel.tsx

- Close #177
- 기능 : DayCarousel UI 수정
- issue : #177 
- sticky 속성을 적용하여, 스크롤 해도 헤더 바로 밑에 위치하게 했습니다. 
- 버튼 UI를 바꿨습니다. 
- 토요일은 파란색, 일요일은 빨간색으로 렌더링 되게 했습니다. 
- 코드 정리가 필요합니다.

feat: DayCarousel UI 수정

---

app/club/[clubId]/league/[leagueId]/match/[matchId]/page.tsx
components/club/TournamentBracket/MatchNode.tsx
components/club/TournamentBracket/index.tsx
components/pages/club/MatchDetail.tsx

- Close #216
- 기능 : match detail 페이지를 생성했습니다. 
- issue : #216
- 토너먼트 노드 클릭하면 페이지 이동하는 것 까지 구현했습니다.

feat: match detail 페이지 생성

---

components/pages/club/ClubIntro.tsx
lib/api/functions/clubMemberFn.ts
lib/api/hooks/clubMemberHook.ts

- Close #221
- 기능 : 동호회 참가 신청 오류 시 toast 띄울 수 있도록 useMutationWithToast 적용하였습니다. 
- issue : #221

feat: 동호회 참가 신청 useMutationWithToast 적용

---

components/pages/club/ClubCreate.tsx
components/pages/club/ClubManage.tsx
lib/api/functions/clubFn.ts
lib/api/hooks/clubHook.ts
lib/api/hooks/useMutationWithToast.ts
types/clubTypes.ts

- Close #228
- 기능 :동호회 생성 안되는 오류 해결
- issue : #228
- useMutationWithToast 의 onSuccessCallback 함수에 매개변수 옵셔널하게 넣을 수 있도록 수정함

fix: 동호회 생성 안되는 오류 해결

---

app/club/[clubId]/layout.tsx
components/pages/MyPage.tsx
components/pages/club/ClubIntro.tsx
components/pages/club/ClubList.tsx
components/pages/club/ClubMember.tsx
lib/api/hooks/clubHook.ts
lib/api/hooks/clubMemberHook.ts
lib/api/hooks/memberHook.ts
lib/api/hooks/useMutationWithToast.ts
lib/api/hooks/useQueryWithToast.ts

- Close #234
- 기능 : 의도하지 않은 곳에서 toast 나오는 에러 해결
- issue : #234
- useGetClubMembersCheck useQuery로 변경
- useGetMembersMyClubs useQuery로 변경
- useQueryWithToast에 enabled 속성 추가
- 회장인 경우에만 동호회 신청 리스트 볼 수 있게 수정

fix: 의도치 않은 toast 에러 나는 것 해결

---

components/pages/club/LeagueDetail.tsx

- Close #244
- 기능 : 대진표 타입 추가 및 경기 상태 추가
- issue : #244

feat: 대진표 타입 추가 및 경기 상태 추가

---

components/pages/myPage/EditProfileDialog.tsx

- Close #246
- 기능 : 프로필 사진 수정 안되는 오류 해결
- issue : #246
- 프로필 사진은 옵셔널하게 제약조건 변경
- 이미지 삭제 후 기본이미지 설정 로직 변경

fix: 프로필 사진 수정 안되는 오류 해결

---

components/pages/club/LeagueDetail.tsx
schemas/schema.d.ts

- Close #248
- 기능 : 경기 생성자만 수정, 삭제 가능하게 수정
- issue : #248
- 경기 생성자가 아닌 경우는 경기 수정, 삭제 하지 못하도록 막았습니다.
- session api와 league 상세 보기 api 의 member token을 이용했습니다.

fix: 경기 생성자만 수정, 삭제 가능하게 수정

---

components/club/LeagueDetail/LeagueInfo.tsx
components/club/LeagueDetail/MatchButton.tsx
components/club/LeagueDetail/ParticipateButton.tsx
components/pages/LiveMatchList.tsx
components/pages/club/LeagueDetail.tsx
lib/api/functions/leagueFn.ts
lib/api/functions/matchFn.ts
lib/api/hooks/leagueHook.ts
lib/api/hooks/matchHook.ts
types/commonTypes.ts
types/leagueTypes.ts
types/matchTypes.ts

- Close #252
- 기능 : 경기 참여 로직 수정
- issue : #252
- 경기 참여 버튼, 대진표 생성 버튼을 컴포넌트로 분리하였습니다. 
- 경기 참여 버튼이 보이는 경우의 수를 적용하였습니다. 
ParticipateButton 컴포넌트의 경우의 수는 `league`의 상태와 사용자 관련 조건(`loginedUser`,`isParticipating`, 티어 비교 등`)에 따라 버튼이 다르게 렌더링됩니다. 아래는 모든 경우의 수를 정리한 것입니다
- 사용자가 참여할 수 있는 경우
- **조건**:
사용자가 로그인 상태이고,
리그 상태가 "RECRUITING" 또는 "RECRUITING_COMPLETED"이고,
모집 인원이 가득 차지 않았으며,
사용자의 티어가 리그 요구사항에 부합하고,
사용자가 아직 참여하지 않은 경우.
**결과**: "경기 참가" 버튼이 렌더링됩니다. 버튼 클릭 시 `handleParticipate(false)`가 호출됩니다.
- 대진표 생성 버튼이 보이는 경우의 수를 적용하였습니다. 
- 리그 상태가 RECRUITING_COMPLETED 또는 PLAYING이고,
대진표가 생성되지 않은 경우, "대진표 생성" 버튼을 렌더링.
- 대진표가 생성된 경우, "대진표 보기" 버튼을 렌더링.
- toast hook이 적용되어 있지 않은 fetch로직을 적용하도록 바꾸었습니다.

fix: 경기 참여 로직 수정

---

components/liveMatch/LeagueStatusButton.tsx
components/liveMatch/LeagueTierBadge.tsx
components/pages/LiveMatchList.tsx

- Close #261
- 기능 :
- issue : #261

feat: 버튼, 뱃지 컴포넌트 화

---

app/club/[clubId]/page.tsx

- Close #269
- 기능 : 클럽 컴포넌트에서 prefetchQuery 적용함
- issue : #269
- 클럽 컴포넌트에서 prefetchQuery 적용하였습니다. 
- 메타 데이터를 적용하였습니다. 
- 버튼, 뱃지 컴포넌트 화는 다른 PR의 커밋이 들어간 것 같습니다.

feat: club 페이지 서버 fetch 구현 및 메타데이터 적용

---

components/club/LeagueForm.tsx
components/pages/club/LeagueCreate.tsx
components/pages/club/LeagueDetail.tsx
components/pages/club/LeagueUpdate.tsx

- Close #299
- 기능 : 경기 생성 시간 관련 에러 처리
- issue : #299
- 경기 시간 이상하게 나오는 에러 해결
- 경기 시간을 한국 시간에 맞게 보내주는 것으로 처리했습니다. 
- 모집 마감 시간 까지 선택할 수 있게 해결
- 이전 시간은 선택 안되도록 막기
- 오늘 이전의 날짜는 선택 못하도록 막았습니다. 
-  경기 모집 마감 시간 시간까지 보여주기

fix: 경기 생성 시간 관련 에러 처리 

---

components/liveMatch/LeagueStatusButton.tsx
components/pages/LiveMatchList.tsx

- Close #302
- 기능 : 메인 페이지 ui 추가
- issue : #302
- 경기 없을 때 처리
- 종료된 경기 ui 에러 처리
- 종료된 경기 버튼이 모집중인 경우 버튼과 ui 가 같아서 border 가 있는 버튼으로 변경함

feat: 메인 페이지 ui 추가

---

components/club/LeagueForm.tsx

- Close #311
- 기능 : 시간 선택 안하면 fetch 안되는 오류 해결
- issue : #311
- 백엔드에 데이터를 전달하려면, 올바른 형식에 맞춰서 보내주어야 합니다. 기존에는 이에 대한 처리 함수로 구현했는데, 이 함수는 시간 input을 선택해야만 동작했습니다. 
- 캘린더에서 날짜 선택할 때도 기본적으로 formatting 된 값을 저장하도록 처리했습니다.

fix: 시간 선택 안하면 fetch 안되는 오류 해결

---

components/DayCell.tsx
components/club/LeagueList/LeagueSchedule.tsx

- Close #317 
- 기능 : 취소된 경기를 다른 경기와 구분해서 보이게 함
- issue : #317 
- 일별 경기 조회 에서 취소된 경기라는 메세지 렌더링
- 월별 경기 조회에서 취소된 경기는 회색 처리
- 반응형도 같이 구현함

feat: 취소된 경기 처리

---

components/club/LeagueDetail/MatchButton.tsx
components/pages/club/LeagueDetail.tsx

- Close #319
- 기능 : 대진표 생성 버튼 조건 맞지 않으면 비활성화
- issue : #319
- 대진표 생성 조건이 맞지 않으면, 비활성화 처리를 하였습니다.
- 버튼의 props 를 줄이고, 컴포넌트 내에서 fetch 처리 하도록 했습니다.

feat: 대진표 생성 버튼 조건 맞지 않으면 비활성화

---

components/club/FreeBracket/MatchCard.tsx
components/club/FreeBracket/index.tsx
components/pages/club/Match.tsx
types/matchTypes.ts

- Close #321
- 기능 :  프리 대진표에서 스코어페이지 연결 및 대진표 반응형 고려
- issue : #321
-  프리 대진표에서 스코어페이지 연결
- 대진표 반응형 고려
- 반응형 고려하면서 단식 ui 를 복식 ui와 동일하게 맞춤
- 컴포넌트로 분리함
- ui 깨지는 오류 해결

feat: 프리 대진표에서 스코어페이지 연결 및 대진표 반응형 고려

---

components/club/ClubForm.tsx
components/pages/myPage/EditProfileDialog.tsx

- Close #323
- 기능 :이미지 미리보기 사용자가 올린 사진 url로 세팅하기
- issue : #323
- 기존은 서버의 데이터 결과로 미리보기를 세팅했습니다. 주소가 response로 보내질 때 그 주소에 이미지 데이터가 늦게 저장 될 가능성이 있다고 백엔드에서 말

fix: 이미지 미리보기 사용자가 올린 사진 url로 세팅하기

---

app/club/[clubId]/page.tsx
lib/api/hooks/clubHook.ts
lib/api/hooks/useQueryWithToast.ts
lib/api/restClient.ts

- Close #324
- 기능 : 동호회 소개 렌더링 에러 해결
- issue : #324
- Next.js의 default 서버 fetch caching 전략: 'force-cache' 이여서, 동호회 소개 페이지에서 렌더링 버벅이는 현상이 발생했습니다. 
- restClient에서 get 요청의 header에 `cache: "no-store"` 설정을 해두었습니다.
- 동호회 소개 페이지는 ssr을 적용하였습니다. ssr 적용을 했기 때문에 서버 컴포넌트에서 fetch 하는데, 서버 컴포넌트에서 fech 성공 후 페이지를 렌더링했음에도 불구하고 클라이언트 컴포넌트에서도 fetch를 시도했습니다. 
- stale time을 적용함으로써 이 현상을 해결하였습니다.

fix: 동호회 소개 페이지 렌더링 버벅이는 현상 해결

---

components/club/ClubForm.tsx
components/pages/myPage/EditProfileDialog.tsx
lib/api/hooks/clubHook.ts
lib/api/hooks/memberHook.ts

- Close #327
- 기능 : 이미지 fetch 결과를 request body에 넣기
- issue : #327
- 이미지 fetching된 결과를 최종적으로 fetch 해야하는 api의 body에 넣어 주었습니다.
에러 상황
수정 상황

fix: 이미지 fetch 결과를 request body에 넣기

---

app/search/page.tsx
components/pages/club/SearchResult.tsx
components/ui/Header.tsx

- Close #329
- 기능 :검색어 제한두기
- issue : #329
- searchParams의 키값을 search로 변경하였습니다.
- 검색 결과는 suspense 컴포넌트로 묶어두었습니다
- [[Next.js 공식문서](https://nextjs.org/docs/app/api-reference/functions/use-search-params#behavior)] We recommend wrapping the Client Component that uses useSearchParams in a <Suspense/> boundary. This will allow any Client Components above it to be statically rendered and sent as part of initial HTML. [Example](https://nextjs.org/docs/app/api-reference/functions/use-search-params#static-rendering). 
- 검색 결과는 50자 이내로 제한해두었습니다.

feat: 검색어 제한두기 (50자)

---

components/club/LeagueDetail/MatchButton.tsx
components/club/ScoreBoard/PlayerScore.tsx
components/club/ScoreBoard/index.tsx
components/pages/club/MatchDetailPage.tsx
lib/api/hooks/matchHook.ts
lib/api/hooks/useMutationWithToast.ts

- Close #335 
- 기능 : 낙관적 업데이트 적용
- issue : #335
- 점수판 업데이트가 제대로 안이루어지는 것을 optimistic update로 전환하여 점수가 항상 올라가는 것 처럼 보이게 했습니다. 
- 사용자 클릭이 많아지는 경우를 대비하여 debounce를 적용하였습니다. 0.3초 단위
- 점수 등록에 toast 훅을 적용하였습니다
- set 변경, 매치 시작을 감지하기 위해 set detail도 폴링으로 구현하였습니다
- 
- 
[이전]
https://github.com/user-attachments/assets/86db517d-faed-481a-810d-e7aecaa4e195
[이후]
https://github.com/user-attachments/assets/9491b8f6-75f4-4241-8ad0-ad99f97a51f5

feat: optimistic update 적용하기
