- app/globals.css
- components/ui/Text.stories.tsx
- components/ui/Text.tsx
- Close #4 
- 기능 : TextComponent를 생성하였습니다. 
- issue : #4
- Text 컴포넌트를 생성하였습니다. 
- props에 따라 다른 css 적용됩니다!
- 해당 컴포넌트는 따로 shadcn에서 가져올 부분이 없어 직접 구현하였습니다. 
- fontSize, fontWeight는 이전에 협의한 것에서 굳이 필요 없다고 생각되는 부분은 제외하고 구현했습니다. 혹시 필요하다고 생각이 들면 언제든 피드백주세요!
- lineClamp는 말줄임 속성입니다. n 줄을 넘어가면 말줄임이 되도록 설정하였습니다.
> feat: Text Component 생성

- components/ui/Grid.stories.tsx
- components/ui/Grid.tsx
- Close #14 
- 기능 : Grid 컴포넌트를 생성합니다.
- issue : #14 
- 그리드 컴포넌트 생성
- flex를 활용하여 만들어 보았습니다.
- 사이즈가 현재 width = 100%, height = 100vh로 설정한 상태입니다. 추후에 변경이 필요할 경우 말씀 해주시면 수정하도록 하겠습니다.
- 반응형에 관해서는 핸드폰의 사이즈를 지정하게 되면 추후에 추가적인 설정을 해주어야 할 것 같습니다. 현재는 따로 설정해주지 않아 기본값으로 적용중입니다.
> feat: Grid 컴포넌트 생성

- components/ui/IconButton.stories.tsx
- components/ui/IconButton.tsx
- Close #19 
- 기능 : IconButton 컴포넌트를 생성합니다.
- issue : #19 
- Button을 참고하여 IconButton을 생성하였습니다.
- 사용시에 Icon은 버튼 내부에 children으로 넣어서 사용해주시면 됩니다.
- Icon의 크기는 %(비율)로 넣어주어야 사이즈 조절 시 같이 변경됩니다.
> feat: IconButton 컴포넌트 생성

- app/(header)/createClub/page.tsx
- Close #26 
- 기능 : 동호회 생성 페이지를 구현 하였습니다.
- issue : #26 
-  band를 참고하여 동호회 생성 페이지를 구현 하였습니다.
- 이름은 input, 사진은 image, 소개는 textarea를 사용하여 구현 하였습니다.
- 이미지 선택의 경우 오른쪽에서 버튼을 클릭해 이미지를 설정하면 왼쪽에서 미리보기를 할 수 있도록 구현 하였는데 혹시 다른 의견이 있으시다면 말씀 부탁드립니다!
> feat: 동호회 생성 페이지 구현

- app/(header)/club/layout.tsx
- app/(header)/club/member/MemberDropdown.tsx
- app/(header)/club/member/OneMemberInfo.tsx
- app/(header)/club/member/page.tsx
- app/(header)/createClub/page.tsx
- middleware.ts
- Close #50 
- 기능 : 린트 에러를 해결했습니다. 
- issue : #50
> chore: Biome 린트 에러 적용

- app/page.tsx
- components/DayCell.tsx
- Close #45 
- 기능 : 캘린더 에 css를 입혔습니다. 
- issue : #45 
- 스케줄 색은 color리스트를 통해 설정되게 구현하였습니다. 
- 한 날짜에 스케줄이 많을 때는 `+N` 으로 나타나게 하였습니다. 
- UI 관련 피드백 환영입니다.
> design: 캘린더 UI 생성

- app/(header)/club/schedule/ScheduleList.tsx
- app/(header)/club/schedule/page.tsx
- app/globals.css
- Close #54 
- 기능 : 스케줄 페이지를 생성하였습니다. 
- issue : #54 
스케줄 페이지를 생성하였습니다. 
- mockdata는 api가 없어 key값과 value값을 제가 그냥 만들었습니다..!
- 메인페이지("/")를 어떻게 해야할지 논의가 필요할 것 같습니다. 
- UI 피드백 환영입니다
> feat: 스케줄 페이지 생성

- app/globals.css
- Close #61 
- 기능 : 다크 모드 주석 처리
- issue : #61
- 안정적인 다크모드 제거를 위해 기존에 작성되었던 다크모드를 주석처리 하였습니다.
> chore: dark 모드 코드 주석 처리

- app/(header)/club/schedule/ScheduleList.tsx
- app/(header)/club/schedule/page.tsx
- Close #64 
- 기능 : 날짜를 클릭하면 해당 날짜 리스트가 나올 수 있도록 날짜 정보를 넘겨줍니다. 
- issue : #64
> feat: 캘린더와 스케줄 리스트 연동

- components/ui/Header.tsx
- Close #65
- 기능 : clubs url에만 검색창이 렌더링 되도록 했습니다. 
- issue : #65
clubs
club 이외
> feat: 헤더 검색창 조건부 렌더링

- app/(header)/club/schedule/ScheduleList.tsx
- app/(header)/club/schedule/league/[leagueId]/page.tsx
- Close #66
- 기능 : 모달로 만들어져 있던 리그 정보를 페이지로 옮겼습니다. 
- issue : #66
> feat: 리그 정보 페이지 추가

- components/clubs/ClubCard.tsx
- components/ui/Header.tsx
- Close #70 
- 기능 : 헤더 컴포넌트와 카드 컴포넌트에 링크 설정을 하였습니다. 
- issue : #70
> chore: 페이지 링크 연결

- app/page.tsx
- Close #72 
- 기능 : 루트 페이지에 redirect 기능을 추가합니다. 
- issue : #72
- 로그인 기능 미구현으로 현재는 /club/intro 로만 이동하게 해두었습니다.
> feat: root page redirect 기능 추가

- .gitignore
- constants/loginOauthUrl.ts
- package.json
- Close #76
- 기능 : 백엔드에서 구현한 setCookie 코드를 가능하게 하기 위해 프론트엔드에서 https 설정을 해두었습니다. 
- issue : #76
> feat: 로그인을 위한 https 환경 세팅

- app/(header)/club/intro/page.tsx
- Close #83 
- 기능 : textarea 에러 수정
- issue : #83 
- textarea는 children을 가질 수 없어 "value"로 props를 넘겨주어 해결 합니다.
> fix: textarea 에러 수정

- package-lock.json
- package.json
- Close #85 
- 기능 : react hook form을 설치했습니다. 
- issue : #85
> chore: react hook form 설치

- app/(header)/clubs/page.tsx
- app/layout.tsx
- lib/Providers.tsx
- lib/TanstackClientProvider.tsx
- Close #88 
- 기능 : tanstack query 세팅을 했습니다. 
- issue : #88 
- tanstack query 세팅을 했습니다. 
- provider는 /lib에 생성하였습니다. 
- 위치에 대한 고민이 있었으나, 결국 이 provider는 라이브러리에 종속되는 것이라 lib 폴더 내부에 두었습니다. 
- clubs에서 테스팅 가능합니다. 
- 해당 내용은 따로 파일을 파서 관리할 예정이니, 참고 부탁드립니다.
> chore: tanstack query 세팅

- app/(header)/club/schedule/ScheduleList.tsx
- app/(header)/club/schedule/create/page.tsx
- components/ui/IconButton.tsx
- components/ui/Input.tsx
- components/ui/dropdown-menu.tsx
- components/ui/popover.tsx
- package-lock.json
- package.json
- Close #93
- 기능 : 경기 생성 페이지를 구현했습니다. 
- issue : #93
- Input 컴포넌트에 text-black이라는 className을 추가했습니다. 
- 제가 만든 컴포넌트를 제외하고 Input을 쓰고 있는 컴포넌트가 없어서 추가했습니다.
- 저희 서비스에서 Input에 다른 color가 들어갈 일이 없을 것 같아서 추가했으나, 다른 color가 필요하다면 리팩토링이 필요할 것 같습니다. 
- dropdown 컴포넌트를 추가했습니다. 
- dropdown을 사용하려면, popover도 설치해야했기 때문에 같이 추가했습니다. 
- IconButton 활용을 위해 className을 추가할 수 있도록 했습니다. 
- dropdown item의 크기 조절을 실패했습니다. 추후 리팩토링이 필요합니다.
> feat: 스케줄 생성 페이지 구현

- app/(header)/createClub/page.tsx
- components/common/clubInfoInput/ClubInfoInputDescription.tsx
- components/common/clubInfoInput/ClubInfoInputName.tsx
- Close #91 
- 기능 : 동호회 생성 페이지 UI 작업을 진행하였습니다.
- issue : #91
- 동호회 생성 페이지를 기존 페이지에서 동호회 소개, 수정 페이지와 비슷한 형태로 다시 만들었습니다.
- UI 작업 중 컴포넌트를 수정했습니다. 변경사항을 동호회 수정 페이지에서도 적용하도록 하겠습니다.
- 추가적인 것이 필요해 보이면 말씀 해주시면 감사하겠습니다!
> design: 동호회 생성 페이지 UI 작업

- app/(header)/my-club/schedule/create/page.tsx
- Close #108
- 기능 : 배포 시 빌드 에러를 해결하였습니다. 
- issue : #108
> fix: 배포 시 나는 에러 해결

- app/login/page.tsx
- Close #119
- 기능 : 구글, 카카오 버튼 삭제
- issue : #119
- 구글 로그인, 카카오 로그인 미구현으로 인해 해당 코드를 삭제했습니다.
> fix: 구글, 카카오 버튼 삭제

- components/ui/Header.tsx
- Close #120 
- 기능 : 로그인 상태일 때 프로필 이미지를 클릭하면 나오는 토글에 기능을 추가했습니다. 
- issue : #120
> feat: header 기능 추가

- app/(header)/club/[clubId]/layout.tsx
- app/layout.tsx
- components/ui/Header.tsx
- lib/api/functions/memberFn.ts
- lib/api/hooks/SessionHook.ts
- Close #148
- 기능 : 권한에 따라 탭 레이아웃 다르게 보이게 구현하였습니다. 
- issue : #148
- 내 동호회가 아닐 때
- 내 동호회일 때
> feat: 권한에 따라 탭 레이아웃 다르게 보이게 하기

- app/(header)/club/[clubId]/schedule/[leagueId]/page.tsx
- constants/loginOauthUrl.ts
- lib/api/functions/leagueFn.ts
- lib/api/hooks/leagueHook.ts
- Close #147 
- 기능 : 동호회 삭제 api 연동했습니다
- issue : #147 
- 백엔드 오류로 직접 확인은 하지 못했습니다. 추후 재확인이 필요합니다.
> feat: 경기 삭제 api 연동

- app/(header)/my/MyOneGameResult.tsx
- app/(header)/my/page.tsx
- lib/api/functions/clubMemberFn.ts
- lib/api/functions/memberFn.ts
- lib/api/hooks/memberHook.ts
- schemas/schema.d.ts
- Close #152 
- 기능 : 내 경기 기록 조회 api 연동
- issue : #152 
- 기록 없을 때도 처리해두었습니다.
> feat: 내 경기 기록 조회 api 연동

- next.config.mjs
> chore: 이미지 도메인 설정

- app/(header)/club/[clubId]/schedule/ScheduleList.tsx
> hotfix: 일반 사용자는 경기 생성을 하지 못하게 함

- components/ui/Header.tsx
> hotfix: 기능 미구현으로 인한 검색창 초기화

- components/ui/Image.tsx
> hotfix: 프로필 이미지 사진 이상하게 나오는 에러 해결

- app/(header)/club/[clubId]/page.tsx
> chore: 매치 결과 오류 해결

- app/(header)/club/[clubId]/page.tsx
- app/(header)/my/MyOneGameResult.tsx
> Hotfix change match result

- app/(header)/club/[clubId]/page.tsx
- components/ui/Header.tsx
> hotfix: 로그인 한 사람만 동호회 가입 가능하도록 변경

- README.md
@hjh010501
안녕하세요 멘토님! 리뷰용 브랜치와 PR 생성하였습니다!
> feat: README 수정

- app/(header)/club/[clubId]/page.tsx
- app/(header)/club/page.tsx
- app/(header)/my/page.tsx
- app/page.tsx
- components/DayCarousel.tsx
- components/ui/Header.tsx
- components/ui/badge.tsx
- components/ui/carousel.tsx
- constants/loginOauthUrl.ts
- lib/api/restClient.ts
- package-lock.json
- package.json
- Close #167
- 기능 : 새로운 메인 페이지를 만들었습니다. 
- issue : #167
- 날짜 carousel을 만들었습니다. 로직적으로 수정이 필요합니다. 
- 경기 리스트를 만들었습니다. UI 수정이 필요합니다. 
- 작업을 위해 권한을 불러오는 api들을 전부 주석 처리 하였습니다. 백엔드 리팩토링 후 새로 배포되기 전까지 필요한 일인 것 같아 commit 하였습니다.
> feat: 새로운 메인 페이지 UI 완성

- app/globals.css
- app/layout.tsx
- components/pages/LiveMatchList.tsx
- components/ui/accordion.tsx
- components/ui/collapsible.tsx
- next.config.mjs
- package-lock.json
- package.json
- tailwind.config.ts
- Close #174
- 기능 : 실시간 매치 결과 볼 수 있는 UI 만들기
- issue : #174
- 실시간으로 match 결과를 볼 수 있게 하는 UI만들었습니다. 
- mockData를 만들어서 구현하였습니다. 
- accordion을 통해 구현하였습니다. 
- 이는 추후 기획이 변경된다면, collapsible 컴포넌트로 변경되어야 합니다. 
- global font도 지정해주었습니다.
> feat: 매치 결과 보는 UI 추가

- app/club/[clubId]/league/[leagueId]/match/page.tsx
- app/club/[clubId]/league/create/page.tsx
- Close #186 
- 기능 : 배포 과정에서 발생한 build 에러를 해결합니다. 
- issue : #186
> hotfix: build 에러 해결

- app/search/page.tsx
- components/pages/club/SearchResult.tsx
- components/ui/Header.tsx
- lib/api/functions/clubFn.ts
- lib/api/hooks/clubHook.ts
- Close #190
- 기능 : 클럽 검색을 구현했습니다. 
- issue : #190
- search 페이지를 만들었습니다. 
- useInfiniteQuery 를 이용해서 클럽 검색을 구현했습니다. 
- 없을 때 UI도 만들었습니다. ( 큰 변화는 아님 )
- 로그인버튼, 검색창도 UI 조금 다듬었습니다.
> feat: 클럽 검색 구현

- components/pages/club/ClubIntro.tsx
- lib/api/functions/clubFn.ts
- lib/api/hooks/clubHook.ts
- Close #200
- 기능 : 동호회 정보 fetch 변경 사항 반영
- issue : #200
> fix: 동호회 정보 fetch 변경사항 반영

- components/pages/LiveMatchList.tsx
- schemas/schema.d.ts
- Close #232
- 기능 : 모집중 routing 연결
- issue : #232
모집중 버튼을 누르면 해당 경기 상세 페이지로 이동합니다.
> feat: 메인페이지 모집중 routing 연결

- lib/api/hooks/useMutationWithToast.ts
- lib/api/hooks/useQueryWithToast.ts
- Close #238
- 기능 :백엔드 common response 변경 반영
- issue : #238
> fix: 백엔드 common response 변경 반영

- components/club/FreeBracket/index.tsx
- Close #242
- 기능 :복식 대진표 생성
- issue : #242
- 메인페이지의 복식 경기 ui 그대로 가져다 썼습니다.
- 데이터 없어 확인 못하고 우선 PR함.
> feat: 복식 대진표 생성

- components/pages/club/LeagueDetail.tsx
- Close #250
- 기능 : 수정, 삭제 깜빡이는 에러 해결
- issue : #250
문제상황
https://cdn.discordapp.com/attachments/1295253729867726869/1309432082467917834/2024-11-22_5.14.39.mov?ex=67418f28&is=67403da8&hm=f77e319591ba15270d60ceecae127fd208044fff26c4bf815292ee15de9999ca&
- 조건문 변경
`loginedUser.data.member_token === league?.league_owner_token` 라면, undefined === undefined 일 가능성이 있으므로, 조건이 참이되어 순간적으로 보이게 되는 현상 발생하였음. 이를 해결하기 위해 조건문을
```
!!loginedUser?.data &&
loginedUser.data.member_token === league?.league_owner_token
```
이렇게 변경하였음
> fix: 수정, 삭제 깜빡이는 에러 해결

- components/pages/club/ClubCreate.tsx
- Close #255
- 기능 : 동호회 생성 validation 추가
- issue : #255
- 유효성 검사 로직 추가 및 디자인 수정
> feat: 동호회 생성 validation 추가

- app/not-found.tsx
- Close #259
- 기능 : 404 페이지 제작
- issue : #259
> feat: add not found page

- components/liveMatch/LeagueStatusButton.tsx
- components/liveMatch/LeagueTierBadge.tsx
- components/pages/LiveMatchList.tsx
> feat: 버튼, 뱃지 컴포넌트 화

- app/club/[clubId]/page.tsx
- components/liveMatch/LeagueStatusButton.tsx
- components/liveMatch/LeagueTierBadge.tsx
- components/pages/LiveMatchList.tsx
- Close #269
- 기능 : 클럽 컴포넌트에서 prefetchQuery 적용함
- issue : #269
- 클럽 컴포넌트에서 prefetchQuery 적용하였습니다. 
- 메타 데이터를 적용하였습니다. 
- 버튼, 뱃지 컴포넌트 화는 다른 PR의 커밋이 들어간 것 같습니다.
> feat: 클럽 컴포넌트에서 prefetchQuery 적용함

- components/club/ClubIntro/ClubParticipateButton.tsx
- components/layouts/ClubLayout.tsx
- components/pages/club/ClubIntro.tsx
- Close #273
- 기능 :동호회 참여 신청 dialog 생성 및 동호회 소개 ui 수정
- issue : #273
> feat: 동호회 참여 신청 dialog 생성 및 동호회 소개 ui 수정

- components/club/ClubMemberApplicants.tsx
- components/club/ClubMemberApplicantsList.tsx
- components/club/ClubMemberBanDialog.tsx
- components/club/ClubMemberBanList.tsx
- components/club/ClubMemberExpelDialog.tsx
- components/club/ClubMemberList.tsx
- components/club/ClubMemberRoleChangeDialog.tsx
- components/pages/club/ClubMember.tsx
- components/ui/table.tsx
- components/ui/tooltip.tsx
- lib/api/functions/clubFn.ts
- lib/api/functions/clubMemberFn.ts
- lib/api/hooks/clubHook.ts
- lib/api/hooks/clubMemberHook.ts
- lib/api/hooks/mainLeagueHook.ts
- lib/api/hooks/useInfiniteQueryReturnFlattenData.ts
- lib/api/hooks/useInfiniteQueryWithFlattenData.ts
- package-lock.json
- package.json
- types/clubMemberTypes.ts
- types/commonTypes.ts
- types/memberTypes.ts
- Close #288 
- 기능 : 동호회 회원 조회 페이지네이션 적용
- issue : #288 
- 동호회 회원 조회 
- 페이지네이션 적용
- 반응형 적용
- 동호회 참여 리스트
- 페이지네이션 적용
- 반응형 적용
- 제재당한 회원 리스트 생성
- 페이지네이션 적용
- 반응형 적용
- 이름 다 안나오는 경우를 대비해서 tooltip 적용
-  스켈레톤 적용을 위해 한 페이지 내에서 fetch n개를 관리하고 있습니다. 이게 맞는 방식인지 잘 모르겠습니다.
> feat: 동호회 회원 조회 페이지네이션 적용

- app/club/[clubId]/league/page.tsx
- components/club/LeagueList.tsx
- components/pages/club/ClubLeaguePage.tsx
- Close #292 
- 기능 : 경기 날짜 searchParam 적용하기
- issue : #292 
- 새로고침해도, 선택한 날짜를 유지하기 위해 searchParam에 date를 적용하였습니다. 
- 날짜가 선택되지 않으면, searchParam은 없으므로 이 경우 오늘 날짜로 보이게 하였습니다.
> feat: 경기 날짜 searchParam 으로 적용하기

- app/club/sitemap.ts
- app/robot.ts
- public/sitemap_index.xml
- Close #300
- 기능 : sitemap, robot.txt 설정
- issue : #300
- google search console 등록을 위한 작업입니다
- index sitemap 파일을 만들고, club sitemap 파일도 따로 만들어 주었습니다. 
- robot.txt 파일 설정을 해두었습니다. allow, disallow 설정을 해두었는데, 최소한만 유지해두었습니다. 공부 후 따로 추가작업이 필요할 것 같습니다.ㅏ
> feat: sitemap, robot.txt 설정

- public/sitemap_index.xml
- Close #305
- 기능 :존재하지 않는 사이트맵 코드 제거
- issue : #305
존재하지 않는 사이트맵 코드를 제거함
> hotfix: 존재하지 않는 사이트맵 코드 제거

- components/club/LeagueDetail/MatchButton.tsx
- components/club/LeagueDetail/ParticipateButton.tsx
- components/club/LeagueDetail/RecruitmentInfoDialog.tsx
- components/pages/club/LeagueDetail.tsx
- Close #307
- 기능 : 경기 상세 정보 가이드라인 추가
- issue : #307
- 반응형 고려
- detail 페이지
- 버튼
- 버튼에 툴팁 적용하여 서비스 정책을 보여줌
- 모집 마감은 모달 적용해 모집 마감 요건을 보여줌
> feat: 경기 상세 정보 가이드라인 추가

- components/club/LeagueDetail/RecruitmentInfoDialog.tsx
- lib/api/functions/leagueFn.ts
- lib/api/hooks/leagueHook.ts
- types/leagueTypes.ts
- Close #309
- 기능 :
- issue : #309 
- 모집 마감 api 연동
> feat: 모집 마감 api 적용

- components/club/LeagueDetail/LeagueParticipant.tsx
- components/pages/club/LeagueDetail.tsx
- types/leagueTypes.ts
- Close #315 
- 기능 : 경기 참여자 리스트 생성
- issue : #315
- 경기 참여자 리스트 생성하였습니다 
- 반응형까지 고려했습니다.
> feat: 경기 참여자 리스트 생성

- components/club/ClubForm.tsx
- components/pages/LiveMatchList.tsx
- components/pages/club/Match.tsx
- lib/api/functions/matchFn.ts
- lib/api/hooks/mainLeagueHook.ts
- lib/api/hooks/matchHook.ts
- lib/api/hooks/useQueryWithToast.ts
- Close #331
- 기능 : 경기 시작 후 메인페이지 accordion 열 때 에러나는 문제 해결
- issue : #331
- 쿼리키 중복으로 인한 에러 발생이였음. 
- 쿼리키 바꿔줌으로써 에러 해결함
- 파라미터 타입 일부 수정
- 타입 단언으로 인해서 오류가 생길 수 있는 부분을 수정했습니다(일부)
> fix: 경기 시작 후 메인페이지 에러나는 문제 해결

- components/club/ScoreBoard/index.tsx
- Close #333
- 기능 : 수정 모드 때 세트 종료 안보이게 수정
- issue : #333
> feat: 수정 모드 때 세트 종료 안보이게 수정

- components/login/LoginButton.tsx
- components/pages/Login.tsx
- Close #336
- 기능 : 로그인 화면 디자인 변경
- issue : #336
[변경전]
[변경후]
> design: 로그인 페이지 ui 변경

- app/club/sitemap.ts
- Close #339
- 기능 :
- issue : #339
해당 에러가 나서, 날짜 형식을 ISO 형식으로 변경하였습니다.
> hot fix: 날짜 형식 변경

- components/club/LeagueDetail/MatchButton.tsx
- components/club/LiveMatchAccordion/LiveMatchCard.tsx
- components/club/ScoreBoard/index.tsx
- components/pages/LiveMatchList.tsx
- Close #343
- 기능 : 메인 페이지 카드 컴포넌트화
- issue : #343
- 메인페이지에서 이름이 길어지면 ui가 깨져서 오류를 수정했습니다
- 해당 카드를 컴포넌트화 했습니다
> feat: 메인페이지 카드 컴포넌트화

- components/club/LeagueDetail/MatchButton.tsx
- components/club/LiveMatchAccordion/LiveMatchCard.tsx
- components/club/ScoreBoard/index.tsx
- components/pages/LiveMatchList.tsx
* feat: 메인페이지 카드 컴포넌트화
* fix: fix biome error
>  deploy: 메인페이지 카드 컴포넌트 화
